
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "agent",
    "mysql/common",
    "mysql/protocol",
    "mysql/binlog",
    "tests",
]

[workspace.dependencies]
tokio = {version = "1.32.0", features = ["full"]}
async-trait = "0.1.73"
uuid = "1.4.1"
# 十六进制数据编码
hex = "0.4.2"
lru = "0.11.0"
bytes = { version = "1" }
thiserror = "1"
serde = { workspace = "1", features = ["derive"] }
bitflags = { version = "2.4.1", features = [] }
