
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "common",
    "binlog",
    "tests",
]

[workspace.dependencies]
tokio = {version = "1.32.0", features = ["full"]}
async-trait = "0.1.73"
uuid = "1.4.1"
# 十六进制数据编码
hex = "0.4.2"
lru = "0.12.1"
bytes = "1.5.0"
thiserror = "1.0.50"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde_yaml = "0.9.27"
structopt = "0.3.16"
bitflags = { version = "2.4.1", features = [] }
nom = "7"
lazy_static = "1.4.0"
flatbuffers = "23.5.26"

log = "0.4.20"
log4rs = "1.2.0"
num_enum = "0.7.1"
byteorder = "1.5.0"
dashmap = "5.5.3"
paste = "1.0.14"
pin-project-lite = "0.2.13"

tracing = "0.1.40"
tracing-subscriber = "0.3.18"

futures-util="^0.3.29"
futures-executor="^0.3.29"

toml = "^0.8.8"
mysql_common = "^0.30.6"

