[package]
name = "common"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
async-trait ={ workspace = true }
uuid = { workspace = true }
hex = { workspace = true }
lru = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
nom = { workspace = true }
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }

futures-util = { workspace = true }
futures-executor = { workspace = true }
tracing = { workspace = true }


log = "0.4.20"
log4rs = "1.2.0"
