[package]
name = "common"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
async-trait ={ workspace = true }
uuid = { workspace = true }
hex = { workspace = true }
lru = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
nom = { workspace = true }
serde = { workspace = true, features = ["derive"] }
toml = { workspace = true }

futures-util = { workspace = true }
futures-executor = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
num_enum = { workspace = true }
mysql_common = { workspace = true }
bigdecimal = { workspace = true }
dashmap = { workspace = true }
once_cell = { workspace = true }

memory = { path = "../memory" }

log = "0.4.20"
log4rs = "1.2.0"
regex = "1.10.2"
